### ISSUE TITLE
Support choosing the schema

### ISSUE THREAD

**Issue by fwgreen** [IBM-Swift/Swift-Kuery-PostgreSQL#2]
Sort of similar to DB2, PostgreSQL puts tables into [schemas](https://www.postgresql.org/docs/current/static/ddl-schemas.html).  If the developer doesn't control the database, there's a possibility of working with tables that are not in the default `public` schema.

**Comment by irar2** [comment]
It is possible to work with a table in a schema by setting the table name as `<schema name>.<table name>`, e.g.:
```swift
    class MySchemaTable: Table {
        let tableName = "myschema.mytable"
        ...
    }
```

**Comment by fwgreen** [comment]
Thanks for taking the time.  Closing.
