### ISSUE TITLE
Missing/minimal support for table fields that are array types.

### ISSUE THREAD

**Issue by TrondKjeldas** [IBM-Swift/Swift-Kuery-PostgreSQL#22]
It seems that there is currently no support for array types, at least not as far as I can find.

The type returned for array is just the binary data returned from libpg, and not an [Any?]? as I would have expected.

I have managed to figure out how to decode the result, and have added rudimentary support for 1-dimmensional text arrays (OID 1009).

Let me know if there is interest in a pull request, but be warned that I would likely need some guidance to get my hack to an acceptable level for merging.

**Comment by kilnerm** [comment]
H @TrondKjeldas, currently, of the three main database plugins supported by SwiftKuery, only PostgreSQL supports the array type and therefore it is unlikely we would consider implementing support for it within the kuery framework.

I am also not clear how I would define a column on a table to be of the array type, do you have an example of how your Swift table is defined so it types the column as an array?

**Comment by TrondKjeldas** [comment]
Hi,

I'm not actively working on the project where this was an issue at the moment, but for what its worth here is a bit more info.

This is the database scheme I used:
```
CREATE TABLE hikes (
    hike_id     SERIAL PRIMARY KEY,
    hike_rev    INTEGER NOT NULL,
    name        TEXT NOT NULL,
    length      REAL NOT NULL,
    description TEXT NOT NULL,
    trackref    TEXT NOT NULL,
    imagerefs   TEXT[4]
);
```
And this was the Swift implementation for the table:
```
final class HikesTable: Table {

    let tableName = "hikes"

    let id    =    Column("hike_id")
    let rev   =    Column("hike_rev")
    let name  =     Column("name")
    let len   = Column("length")
    let  desc = Column("description")
    let trackref = Column("trackref")
    let imagerefs = Column("imagerefs")
}

extension Hike : FieldMappable {

  public init?(fields: [String: Any]) {

    var id: Int = 2
    if let id32 = fields["hike_id"] as? Int32 {
        id = Int(id32)
    } else {
        return nil
    }

    let revision = Int(fields["hike_rev"] as! Int32)
    let name = fields["name"] as! String
    let length = Double(fields["length"] as! Float)
    let description = fields["description"] as! String
    let trackRef = fields["trackref"] as! String
    var imagesRef: [String]  = []
    if let imgs = fields["imagerefs"] as? [Any?] {
      for i in imgs {
        if let i = i as? String {
          imagesRef.append(i)
        }
      }
    }

    self = Hike(id:id, revision:revision, name:name, length:length,
            description:description, trackRef:trackRef, imagesRef:imagesRef)
  }
}
```

**Comment by kilnerm** [comment]
Given the lack of support for the array column type in MySQL and SQLite I am going to mark this as closed as it is not something we will pursue at this time.
