### ISSUE TITLE
Failed Authentication 

### ISSUE THREAD

**Issue by t3ndai** [IBM-Swift/Swift-Kuery-PostgreSQL#25]
SwiftKuery PostgreSQL is failing to throws an Error on failed connections e.g if a username/password is wrong 
e.g  guard let connection = pool.getConnection() else { throw SwiftKueryError.failedConnection }
if you a connection can't be established on a completion handler it just returns an empty instead of reporting the error  

```Swift

let pool = PostgreSQLConnection.createPool(host: "localhost", port: 5432, options: [/*.userName("xxxxx"), .password("xxxxx"),*/ .databaseName("dollar")], poolOptions: ConnectionPoolOptions(initialCapacity: 10, maxCapacity: 50, timeout: 10000))
func majorAverages(_ completion: @escaping ([[String: Any]]) -> Void) throws {
    
    guard let connection = pool.getConnection() else { throw SwiftKueryError.failedConnection }
    var averages: [[String: Any]] = [[:]]

    let avgQuery = Select(jobs.major, avg(jobs.pay).as("average"), from: jobs)
        .group(by: jobs.major)
        .order(by: .DESC(avg(jobs.pay)))
    
    
    connection.execute(query: avgQuery){ result in
        
        if let rows = result.asRows {
            
            averages = rows
            completion(averages)
        }
        else if let queryError = result.asError {
            print("Something went wrong")
        }
        
    }
    
}
```

Connection is not being consistent. If you use a connection with a just a database name it connects and fails at times. With userName and password same thing.

**Comment by t3ndai** [comment]
I would also recommend a failed connection to be Fatal!.

**Comment by kilnerm** [comment]
I have raised an issue on the SwiftKuery project to address the issue of not exposing connection errors to users:

https://github.com/IBM-Swift/Swift-Kuery/issues/158

I think SwiftKuery should do this but I believe we should leave the user to decide whether they wish to fail in a fatal fashion.
