### ISSUE TITLE
Reusing Prepared Statements

### ISSUE THREAD

**Issue by ralischer** [IBM-Swift/Swift-Kuery-PostgreSQL#28]
Hi, I'm trying to reuse a prepared statement with a "RETURNING id" suffix on insert but only approximetly each second row is returning the inserted id or is even executed. 

I tried to insert 10683 rows but only 5323 rows are inserted correctly. When I prepare each statement for itself all 10683 rows are inserted.

**Comment by kilnerm** [comment]
Hi @ralischer, did you ever resolve this issue? If you need some further assistance could you please update the issue with some sample code demonstrating how you are creating and calling your prepared statement?

**Comment by kilnerm** [comment]
I'm going to close this, should further assistance be required please reopen.
