### ISSUE TITLE
Where clause

### ISSUE THREAD

**Issue by azamsharp** [IBM-Swift/Swift-Kuery-PostgreSQL#30]
How can we write a delete query with a where clause? 

 let deleteQuery = Delete(from: dishes).where(dishes.key == dish.id)

**Comment by EnriqueL8** [comment]
hey @azamsharp , did you manage to execute the query? That Delete query looks fine to me if the `dishes.key` is a column in the table `dishes`.

**Comment by kilnerm** [comment]
Hi @azamsharp, if you need further help with this please reopen the issue and let me know.
