### ISSUE TITLE
Does it support PostgreSQL-10?

### ISSUE THREAD

**Issue by diuming** [IBM-Swift/Swift-Kuery-PostgreSQL#44]
Hi Master,

OS: Ubuntu 16.04
Swift: 4.0.3

I installed `PostgresSQL-10`, `libpq-dev(libpq-dev is already the newest version (10.2-1.pgdg16.04+1)) "the libpq-fe.h in /usr/include/postgresql folder already"` and rebuild it, but I got some messages(following).
Does it support PostgresSQL-10? or do I miss some steps?
thanks for helping me.

-----------------------------------------------------------------------
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "shim.h"
         ^
/home/abc/code/KituraWeb/.build/checkouts/CLibpq.git--3882173707137841795/shim.h:21:9: error: 'libpq-fe.h' file not found
#import <libpq-fe.h>
        ^
/home/abc/code/KituraWeb/.build/checkouts/Swift-Kuery-PostgreSQL.git-3922437663546017265/Sources/SwiftKueryPostgreSQL/PostgreSQLConnection.swift:18:8: error: could not build C module 'CLibpq'
import CLibpq

**Comment by EnriqueL8** [comment]
hey @diuming ,  could you show me the contents of this file `/etc/apt/sources.list.d/pgdg.list`?

**Comment by diuming** [comment]
Hi @EnriqueL8 , Thanks!
There are no any files in /etc/apt/sources.list.d/ folder.

Do you need it? (/etc/apt/sources.list)
-------------------------------------------------------------------------
@kitura:/etc/apt$ more sources.list
# 

# deb cdrom:[Ubuntu-Server 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801)]/ xenial main restricted

# deb cdrom:[Ubuntu-Server 16.04.3 LTS _Xenial Xerus_ - Release amd64 (20170801)]/ xenial main restricted

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://us.archive.ubuntu.com/ubuntu/ xenial main restricted
# deb-src http://us.archive.ubuntu.com/ubuntu/ xenial main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates main restricted
# deb-src http://us.archive.ubuntu.com/ubuntu/ xenial-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://us.archive.ubuntu.com/ubuntu/ xenial universe
# deb-src http://us.archive.ubuntu.com/ubuntu/ xenial universe
deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates universe
# deb-src http://us.archive.ubuntu.com/ubuntu/ xenial-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
## team, and may not be under a free licence. Please satisfy yourself as to 
## your rights to use the software. Also, please note that software in 
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://us.archive.ubuntu.com/ubuntu/ xenial multiverse
# deb-src http://us.archive.ubuntu.com/ubuntu/ xenial multiverse
deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates multiverse
# deb-src http://us.archive.ubuntu.com/ubuntu/ xenial-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://us.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse
# deb-src http://us.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu xenial partner
# deb-src http://archive.canonical.com/ubuntu xenial partner

deb http://security.ubuntu.com/ubuntu xenial-security main restricted
# deb-src http://security.ubuntu.com/ubuntu xenial-security main restricted
deb http://security.ubuntu.com/ubuntu xenial-security universe
# deb-src http://security.ubuntu.com/ubuntu xenial-security universe
deb http://security.ubuntu.com/ubuntu xenial-security multiverse
deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
# deb-src http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
# deb-src http://security.ubuntu.com/ubuntu xenial-security multiverse

**Comment by diuming** [comment]
Hi @EnriqueL8,
Finally! I using the "swift build -Xcc -I/usr/include/postgresql" command to resolve my problem.
