### ISSUE TITLE
Cannot build if main.swift exists

### ISSUE THREAD

**Issue by Keno42** [IBM-Swift/Swift-Kuery-PostgreSQL#46]
## Description
It cannot build if the project has `main.swift` under the ./Source directory

## Environment
$ swift --version
Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
Target: x86_64-apple-macosx10.9

## Reproduction step
1. `$ swift package init --type executable` in a new directory
2. Add `.package(url: "https://github.com/IBM-Swift/Swift-Kuery-PostgreSQL", .upToNextMinor(from: "1.0.0"))` and `dependencies: ["SwiftKueryPostgreSQL"])` in the `Package.swift` as the README says
3. `$ swift build`

## Actual Result
It fails to build by showing `error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /<your path>/.build/debug.yaml main`

## Expected Result
It builds

---
I am not very sure what is a core problem here. ~~Is it by design that it requires the project not having `main.swift`? Is there any workaround other than renaming the file?~~ Is there any workaround?

**Comment by EnriqueL8** [comment]
hey @Keno42, I just tried it following the same steps and the swift build worked. Maybe this could help? https://stackoverflow.com/questions/25889723/swift-failed-with-exit-code-1-while-compiling-in-xcode-possibly-related-to-bri

**Comment by Keno42** [comment]
@EnriqueL8: Thank you for your help. I will check the thread and try their solutions and report back here.

**Comment by Keno42** [comment]
Turned out something in my homebrew was outdated too much to cause the issue.

Did not work:
```
$ brew uninstall postgresql
$ brew install postgresql
```

Did work:
```
$ brew upgrade
```

Not sure which one caused the issue though.. Sorry for the noise. Thank you!
