### ISSUE TITLE
Build error libpq-fe.h

### ISSUE THREAD

**Issue by syndia** [IBM-Swift/Swift-Kuery-PostgreSQL#5]
Hello,

when I imported Swift-Kuery-PostgressSQL in my app I get build error libpq-fe.h was not found.

I'm using postgres app from postgresapp.com, after searching i found on their site the solution.
Maybe you can put it in the wiki or front document. So people don't have to search hard.

#import <libpq-fe.h>
Then make sure to link with libpq.
On iOS, you'll need to build libpq yourself.
On macOS you can use the system provided libpq (does not support SSL) or use libpq provided by Postgres.app by adding the following build settings:

Other Linker Flags	-lpq
Header Search Paths	/Applications/Postgres.app/Contents/Versions/latest/include
Library Search Paths	/Applications/Postgres.app/Contents/Versions/latest/lib

**Comment by arslan2012** [comment]
on Linux you need to
`sudo apt-get install libpq-dev`

**Comment by irar2** [comment]
Right, and this is also written in the readme.

**Comment by clausguttesen** [comment]
Macport is also used to install packages on mac.
