### ISSUE TITLE
All select queries returning successNoData

### ISSUE THREAD

**Issue by bridger** [IBM-Swift/Swift-Kuery-PostgreSQL#52]
I'm seeing my SELECT queries appear to succeed, but they are returning no data. The result is always successNoData.

This started happening after I updated to 1.2.0. I was running a much older fork before today.

Here is a simple example which definitely should return data, but doesn't return anything for me:

```
    let select = Select(documents.documentId , from: documents)
    connection.execute(query: select) { result in
        guard result.success else {
            print("the query succeeds, so this print doesn't happen")
            return
        }

        if let resultSet = result.asResultSet {
            print("This print never runs")
        } else if case .successNoData = result {
            print("This always prints every time, no matter what select statement I try")
        }
    }
```

**Comment by bridger** [comment]
It looks like maybe all queries are failing. I tried an update query. It also returned successNoData, but I don't see the change in my database.

I'm not sure if maybe the update isn't sticking because of a transaction change or something. In the previous version I wasn't using explicit transactions but maybe I need to now?

**Comment by kilnerm** [comment]
@bridger - Can you share you table definition and how you are creating the database connection?

My immediate thought is that this could be related to the changes to respect case sensitivity. Are you running against a previously created database?

**Comment by bridger** [comment]
Holy smokes! I didn't know Postgres was case sensitive!  That was my bug. I had two tables with the same name (but different case) and now it selects from the bad table.

I'm sorry for the trouble here. Thank you for helping me find my bug!

**Comment by kilnerm** [comment]
Hi @bridger, To clarify, by default postgres will lowercase any name you pass into it. You can work around this behavior by wrapping names in quotes.

As SwiftKuery is an abstraction layer we need it's behavior to be consistent across all the database plugins so made the change in SwiftKuery 2.0.0 to ensure casing is respected regardless of the plugin being used.
