### ISSUE TITLE
Missing CLibpq module

### ISSUE THREAD

**Issue by Cabdude** [IBM-Swift/Swift-Kuery-PostgreSQL#6]
Idk why or if it is just me but when I import to use on Xcode

I get this error 

`import SwiftKuery`
`import SwiftKueryPostgreSQL  -Missing required module 'CLibpq'`

Am I doing this right?

I brew installed postgresql

I tried brew install libpqxx

Import SwiftKuery has no issues. I tried doing swift build to see if that had any effect but it doesn't. When I did swift build I tried making the search path go to the CLibpq folder with no luck. Im lost as to how to fix this.

**Comment by shmuelk** [comment]
Does your project build if you use the Swift Package Manager (SPM) (i.e. swift build) ?

I assume that you generated your project using SPM (i.e. swift package generate-xcodeproj) ?

**Comment by Cabdude** [comment]
I generated my project using Xcode than added the SwiftKuery and SwiftKueryPostgreSQL as build dependencies. It could be Xcode just not linking something right. Idk.

**Comment by shmuelk** [comment]
When you add dependencies to your project, you should add then to your Package.swift file and then regenerate the XCode project using `swift package generate-xcodeproj`

**Comment by kweinmeister** [comment]
@Cabdude are you still seeing this issue on Xcode 8.3.3, Swift 3.1.1, and the latest version of this project?

**Comment by AkshayNG** [comment]
> When you add dependencies to your project, you should add then to your Package.swift file and then regenerate the XCode project using `swift package generate-xcodeproj`

@shmuelk I did. But still no luck.

**Comment by shmuelk** [comment]
@AkshayNG I apologise for asking the obvious, but you have installed the PostgreSQL client libraries? Also is this problem on Linux or on MacOS?

**Comment by AkshayNG** [comment]
@shmuelk Sorry. I didn't get with the PostgreSQL client libraries. I just followed the step whatever given in the README

<img width="623" alt="Screenshot 2019-04-07 at 4 29 26 PM" src="https://user-images.githubusercontent.com/15035623/55682537-998f3380-5952-11e9-8b22-2af78215eb0b.png">

<img width="1270" alt="Screenshot 2019-04-07 at 4 32 06 PM" src="https://user-images.githubusercontent.com/15035623/55682553-d2c7a380-5952-11e9-95f1-e013b3e4e268.png">

<img width="974" alt="Screenshot 2019-04-07 at 4 32 21 PM" src="https://user-images.githubusercontent.com/15035623/55682560-e96dfa80-5952-11e9-9642-629e9b06bdfc.png">

**Comment by shmuelk** [comment]
Do you have pkg-config installed?

If not, it can be installed via `brew install pkg-config` ?

**Comment by AkshayNG** [comment]
After running `brew install pkg-config` I got: 
pkg-config 0.29.2 is already installed and up-to-date.

**Comment by kilnerm** [comment]
CLipq should be generated when building the project.

What output do you get if you run `pkg-config --libs libpq`?

**Comment by AkshayNG** [comment]
@kilnerm Hi, with `pkg-config --libs libpq` :

<img width="447" alt="Screenshot 2019-04-09 at 11 05 22 PM" src="https://user-images.githubusercontent.com/15035623/55821895-23d6c380-5b1c-11e9-845c-16c6acc17392.png">

**Comment by kilnerm** [comment]
Can you move the dependency declaration for SwiffKueryORM and SwiftKueryPostgreSQL from the PGSQL target to the Application target and try building again please?

**Comment by AkshayNG** [comment]
> Can you move the dependency declaration for SwiffKueryORM and SwiftKueryPostgreSQL from the PGSQL target to the Application target and try building again please?

This worked !! Thanks @kilnerm 👍 :)
I would like to know whats the trick there.

**Comment by mesas978** [comment]
AkshayNG, could you share your successful Package.swift ?
