### ISSUE TITLE
UnsafeRawPointer(String) is wrongfully assumed to return a null terminated UTF8 string

### ISSUE THREAD

**Issue by moshegottlieb** [IBM-Swift/Swift-Kuery-PostgreSQL#62]
In `PosgreSQLConnection.execute(query: String?, preparedStatement: PreparedStatement?, with parameters: [Any?], onCompletion: @escaping ((QueryResult) -> ()))`:  
Before binding parameters (string only, it appears) using _libpq_, the code assumes `UnsafeRawPointer(String)` returns a null terminated UTF8 C string.  
This is wrong, String's internal implementation may return any type of data it sees fit to use.  
In fact, the string is never guaranteed to be null terminated, and by sheer luck, this is mostly the case.  
Under some circumstances (and never on macOS, always on Linux) we got weird messages complaining about non UTF8 data in our strings.  
After a brief investigation we found the issue and fixed it in our branch - see pull request #61.  
The trick is to make sure the data is actually UTF8 (by converting the string to data, using the UTF8 encoding) and then allocating the buffer, copy the data and force null termination.

**Comment by kilnerm** [comment]
This was resolved under PR #79
