### ISSUE TITLE
Cannot get packages for Swift-Kuery-PostgreSQL in Xcode

### ISSUE THREAD

**Issue by mprecke** [IBM-Swift/Swift-Kuery-PostgreSQL#69]
When I integrate the dependencies in my packages.swift file, I cannot fetch and use them due to issues with:
- CLibpq.git--8701709317686881875: warning: Ignoring declared target(s) 'CLibpq' in the system package
- CommonCrypto.git--7602333819609117700: warning: Ignoring declared target(s) 'CommonCrypto' in the system package
- CCurl.git--1492179406688812782: warning: Ignoring declared target(s) 'CCurl' in the system package

I am unfortunately unable to solve this issue and would appreciate any assistance.

**Comment by kilnerm** [comment]
@mprecke, sorry it's taken so long to get back to you!! Could you please add the contents of your Package.swift file for me to take a look at? Thanks.

**Comment by mprecke** [comment]
@kilnerm don't worry, I was away for the holidays as well. the content of my packages.swift file is as follows

import PackageDescription

let package = Package(
    name: "NoiseGateServer",
    dependencies: [
      .package(url: "https://github.com/IBM-Swift/Kitura.git", .upToNextMinor(from: "2.3.0")),
      .package(url: "https://github.com/IBM-Swift/HeliumLogger.git", .upToNextMinor(from: "1.7.1")),
      .package(url: "https://github.com/IBM-Swift/CloudEnvironment.git", from: "7.1.0"),
      .package(url: "https://github.com/RuntimeTools/SwiftMetrics.git", from: "2.0.0"),
      .package(url: "https://github.com/IBM-Swift/Health.git", from: "1.0.0"),
      .package(url: "https://github.com/IBM-Swift/Swift-Kuery-ORM.git", .upToNextMinor(from: "0.0.1")),
      .package(url: "https://github.com/IBM-Swift/Swift-Kuery-PostgreSQL.git", .upToNextMinor(from: "1.1.0"))
    ],
    targets: [
      .target(name: "NoiseGateServer", dependencies: [ .target(name: "Application"), "Kitura" , "HeliumLogger"]),
      .target(name: "Application", dependencies: [ "Kitura", "CloudEnvironment","SwiftMetrics","Health", "SwiftKueryORM", "SwiftKueryPostgreSQL"]),

      .testTarget(name: "ApplicationTests" , dependencies: [.target(name: "Application"), "Kitura","HeliumLogger" ])
    ]
)


I also tried with newer versions of Swift-Kuery-PostgreSQL and Swift-Kuery-ORM but it had no effect. I am using a Mac with the latest version of Mohave.Let me know if you need any more information. thank you

**Comment by kilnerm** [comment]
What version of swift are you using?

At what point do you see the warnings, do they occur when doing package resolution, `swift package resolve` or is it when building, `swift build`?

**Comment by kilnerm** [comment]
@mprecke, are you still seeing this issue? If so can you give me the details I asked for in my previous comment? Thanks.

**Comment by kilnerm** [comment]
Marking this as closed, wil re-open if further information becomes available.
